/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import domainmodels.ChucVu;
import infrastructure.convert.FormUtil;
import java.util.UUID;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import reponces.QLRam;
import reponces.QlChucVu;
import reponces.QlKhachHang;
import reponces.QlUser;
import services.impl.ChucVuServiceImpl;
import services.impl.RamServiceImpl;
import services.impl.UserServiceImpl;

/**
 *
 * @author TranCongHieu
 */
public class ViewNhanVien extends javax.swing.JFrame {

    DefaultTableModel tableModel;
    UserServiceImpl userServiceImpl;
    ChucVuServiceImpl chucvuServiceimpl;

    /**
     * Creates new form ViewNhanVien
     */
    public ViewNhanVien() {
        initComponents();
        chucvuServiceimpl = new ChucVuServiceImpl();
        this.setLocationRelativeTo(null);
        this.tableModel = (DefaultTableModel) tableNhanVien.getModel();
        this.userServiceImpl = new UserServiceImpl();
        String title[] = {"STT", "Mã NV", "Họ Tên", "Địa chỉ", "SDT", "Giới tính", "CCCD", "Trạng thái", "Mật khẩu", "Chức vụ"};
        this.tableModel.setColumnIdentifiers(title);
        loadDataOnTable();
    }

    private void loadDataOnTable() {
        this.tableModel.setRowCount(0);
//        for (QLRam qlRam : this.ramServiceImpl.findAll()) {
//            tableModel.addRow((Object[]) qlRam.getData());
        for (QlUser qluser : this.userServiceImpl.findAll()) {
            tableModel.addRow((Object[]) qluser.getData(WIDTH));
        }
    }

    public Boolean Validateform() {
        String ten = txthoten.getText().trim();
        
        String diaChi = txtdiachi.getText().trim();
        String sdt = txtsdt.getText().trim();
        String matkhau = txtmatkhau.getText().trim();
        String cccd = txtcccd.getText().trim();
        if (ten.isBlank() || diaChi.isBlank() || sdt.isBlank() || matkhau.isBlank() || cccd.isBlank()) {
            JOptionPane.showMessageDialog(this, "Mời bạn nhập đầy đủ dữ liệu");
            return false;
        }
        if (!sdt.matches("0+\\d{9}")) {
            JOptionPane.showMessageDialog(this, "Số điện thoại phải 10 số và bắt đầu từ 0");
            return false;
        }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        btnthem = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txttimkiemten = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txthoten = new javax.swing.JTextField();
        txtsdt = new javax.swing.JTextField();
        txtdiachi = new javax.swing.JTextField();
        txtmatkhau = new javax.swing.JTextField();
        rdnam = new javax.swing.JRadioButton();
        rdnu = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtcccd = new javax.swing.JTextField();
        rdhoatdong = new javax.swing.JRadioButton();
        rdkhonghoatdong = new javax.swing.JRadioButton();
        rdnhanvien = new javax.swing.JRadioButton();
        rdquanli = new javax.swing.JRadioButton();
        btnsua = new javax.swing.JButton();
        btnmoi = new javax.swing.JButton();
        btnxoa = new javax.swing.JButton();
        btnthoat = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableNhanVien = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnthem.setIcon(new javax.swing.ImageIcon("C:\\Users\\TranCongHieu\\Documents\\DUAN1\\src\\main\\java\\images\\Save.png")); // NOI18N
        btnthem.setText("Thêm");
        btnthem.setToolTipText("");
        btnthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("QUẢN LÍ NHÂN VIÊN");

        jLabel2.setText("Tìm theo tên:");

        txttimkiemten.setActionCommand("<Not Set>");
        txttimkiemten.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txttimkiemtenCaretUpdate(evt);
            }
        });

        jLabel3.setText("Họ tên");

        jLabel4.setText("SDT");

        jLabel5.setText("Địa chỉ");

        jLabel6.setText("Mật khẩu");

        jLabel7.setText("Giới tính");

        buttonGroup1.add(rdnam);
        rdnam.setText("Nam");

        buttonGroup1.add(rdnu);
        rdnu.setText("Nữ");

        jLabel9.setText("CCCD");

        jLabel10.setText("Trạng thái");

        jLabel11.setText("Chức vụ");

        buttonGroup2.add(rdhoatdong);
        rdhoatdong.setText("Hoạt động");

        buttonGroup2.add(rdkhonghoatdong);
        rdkhonghoatdong.setText("Không hoạt động");

        buttonGroup3.add(rdnhanvien);
        rdnhanvien.setText("Nhân viên");

        buttonGroup3.add(rdquanli);
        rdquanli.setText("Quản lí");

        btnsua.setIcon(new javax.swing.ImageIcon("C:\\Users\\TranCongHieu\\Documents\\DUAN1\\src\\main\\java\\images\\Edit.png")); // NOI18N
        btnsua.setText("Sửa");
        btnsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuaActionPerformed(evt);
            }
        });

        btnmoi.setIcon(new javax.swing.ImageIcon("C:\\Users\\TranCongHieu\\Documents\\DUAN1\\src\\main\\java\\images\\Add.png")); // NOI18N
        btnmoi.setText("Mới");
        btnmoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmoiActionPerformed(evt);
            }
        });

        btnxoa.setIcon(new javax.swing.ImageIcon("C:\\Users\\TranCongHieu\\Documents\\DUAN1\\src\\main\\java\\images\\Delete.png")); // NOI18N
        btnxoa.setText("Xóa");
        btnxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoaActionPerformed(evt);
            }
        });

        btnthoat.setIcon(new javax.swing.ImageIcon("C:\\Users\\TranCongHieu\\Documents\\DUAN1\\src\\main\\java\\images\\Exit.png")); // NOI18N
        btnthoat.setText("Thoát");
        btnthoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthoatActionPerformed(evt);
            }
        });

        tableNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableNhanVienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableNhanVien);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnthem)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txttimkiemten, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtdiachi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                                        .addComponent(txtsdt, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txthoten, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(btnsua)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(rdnam, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(rdnu, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(50, 50, 50)
                                        .addComponent(btnmoi)))
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnxoa)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtcccd, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rdhoatdong)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rdkhonghoatdong))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rdnhanvien)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rdquanli))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnthoat)
                                .addGap(29, 29, 29))
                            .addComponent(txtmatkhau, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txttimkiemten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnthoat))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txthoten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtmatkhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtsdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtcccd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtdiachi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(rdhoatdong)
                    .addComponent(rdkhonghoatdong))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(rdnhanvien)
                    .addComponent(rdquanli)
                    .addComponent(jLabel7)
                    .addComponent(rdnam)
                    .addComponent(rdnu))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnthem)
                    .addComponent(btnsua)
                    .addComponent(btnmoi)
                    .addComponent(btnxoa))
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnthoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthoatActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnthoatActionPerformed

    private void btnmoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmoiActionPerformed
        // TODO add your handling code here:
        txttimkiemten.setText(null);
        txthoten.setText(null);
        txtsdt.setText(null);
        txtdiachi.setText(null);
        txtmatkhau.setText(null);
        
        txtcccd.setText(null);
        buttonGroup1.clearSelection();
        buttonGroup2.clearSelection();
        buttonGroup3.clearSelection();
        loadDataOnTable();
    }//GEN-LAST:event_btnmoiActionPerformed

    private void btnthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemActionPerformed

        if (Validateform()) {
            String ten = txthoten.getText().trim();
            String ma=userServiceImpl.genMaTuDong();
            String diaChi = txtdiachi.getText().trim();
            String sdt = txtsdt.getText().trim();
            String matkhau = txtmatkhau.getText().trim();
            String cccd = txtcccd.getText().trim();
            boolean gioitinh = true;
            if (rdnam.isSelected()) {
                gioitinh = false;
            }
            int trangthai = 1;
            if (rdhoatdong.isSelected()) {
                trangthai = 0;
            }

            QlChucVu qlchucvu1 = new QlChucVu();
            if (rdnhanvien.isSelected()) {
                qlchucvu1 = chucvuServiceimpl.findOne("NV");
            } else {
                qlchucvu1 = chucvuServiceimpl.findOne("QL");
            }

            QlUser qluser = new QlUser(ma, ten, diaChi, sdt, cccd, gioitinh, trangthai, sdt, matkhau, FormUtil.convertFromQlChucVuToChucVu(qlchucvu1));
            String text = this.userServiceImpl.save(qluser);
            JOptionPane.showMessageDialog(rootPane, text);
            loadDataOnTable();
        }
    }//GEN-LAST:event_btnthemActionPerformed
    private void findDataOnUser(String name) {
        tableModel.setRowCount(0);
        int i = 0;
        for (QlUser qluser : this.userServiceImpl.findAllByNv(name)) {
            tableModel.addRow((Object[]) qluser.getData(i));
            i++;
        }
    }


    private void tableNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableNhanVienMouseClicked
        // TODO add your handling code here:
        int row = tableNhanVien.getSelectedRow();
        txthoten.setText(tableNhanVien.getValueAt(row, 2).toString());
        txtdiachi.setText(tableNhanVien.getValueAt(row, 3).toString());
        txtsdt.setText(tableNhanVien.getValueAt(row, 4).toString());
        txtcccd.setText(tableNhanVien.getValueAt(row, 6).toString());
        txtmatkhau.setText(tableNhanVien.getValueAt(row, 8).toString());
        if (tableNhanVien.getValueAt(row, 5).toString().equalsIgnoreCase("Nam")) {
            rdnam.setSelected(true);
        } else {
            rdnu.setSelected(true);

        }
        if (tableNhanVien.getValueAt(row, 7).toString().equalsIgnoreCase("Hoạt động")) {
            rdhoatdong.setSelected(true);
        } else {
            rdkhonghoatdong.setSelected(true);
        }
        if (tableNhanVien.getValueAt(row, 9).toString().equalsIgnoreCase("Nhân viên")) {
            rdnhanvien.setSelected(true);
        } else {
            rdquanli.setSelected(true);
        }


    }//GEN-LAST:event_tableNhanVienMouseClicked

    private void txttimkiemtenCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txttimkiemtenCaretUpdate
        // TODO add your handling code here:
        String manv = txttimkiemten.getText().trim();
        findDataOnUser(manv);

    }//GEN-LAST:event_txttimkiemtenCaretUpdate

    private void btnsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuaActionPerformed
        // TODO add your handling code here:
        String ten = txthoten.getText().trim();
        
        String diaChi = txtdiachi.getText().trim();
        String sdt = txtsdt.getText().trim();
        String matkhau = txtmatkhau.getText().trim();
        String cccd = txtcccd.getText().trim();
        boolean gioitinh = true;
        if (rdnam.isSelected()) {
            gioitinh = false;
        }
        int trangthai = 1;
        if (rdhoatdong.isSelected()) {
            trangthai = 0;
        }

        QlChucVu qlchucvu1 = new QlChucVu();
        if (rdnhanvien.isSelected()) {
            qlchucvu1 = chucvuServiceimpl.findOne("NV");
        } else {
            qlchucvu1 = chucvuServiceimpl.findOne("QL");
        }
        int row = tableNhanVien.getSelectedRow();
        if (row == - 1) {
            JOptionPane.showMessageDialog(rootPane, "Bạn phải chọn 1 dòng tương ứg");
            return;
        }
        if (Validateform()) {
            String ma = tableNhanVien.getValueAt(row, 1).toString();
            QlUser qluser = this.userServiceImpl.findOne(ma);

            qluser.setTen(ten);
            
            qluser.setDiaChi(diaChi);
            qluser.setMatKhau(matkhau);
            qluser.setCccd(cccd);
            qluser.setSdt(sdt);
            qluser.setGioiTinh(gioitinh);
            qluser.setTrangThai(trangthai);
            qluser.setIdChucVu(FormUtil.convertFromQlChucVuToChucVu(qlchucvu1));
            String text = this.userServiceImpl.update(qluser);
            JOptionPane.showMessageDialog(this,"Sửa thành công");
            loadDataOnTable();
        }
    }//GEN-LAST:event_btnsuaActionPerformed

    private void btnxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoaActionPerformed
        // TODO add your handling code here:
        int row = tableNhanVien.getSelectedRow();
        if (row == - 1) {
            JOptionPane.showMessageDialog(rootPane, "Bạn phải chọn 1 dòng tương ứg");
            return;
        }
        String ma = tableNhanVien.getValueAt(row, 1).toString();
        QlUser qluser = this.userServiceImpl.findOne(ma);
        String text = this.userServiceImpl.delete(qluser);
        JOptionPane.showMessageDialog(rootPane,"Xóa thành công");
        loadDataOnTable();
    }//GEN-LAST:event_btnxoaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewNhanVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnmoi;
    private javax.swing.JButton btnsua;
    private javax.swing.JButton btnthem;
    private javax.swing.JButton btnthoat;
    private javax.swing.JButton btnxoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdhoatdong;
    private javax.swing.JRadioButton rdkhonghoatdong;
    private javax.swing.JRadioButton rdnam;
    private javax.swing.JRadioButton rdnhanvien;
    private javax.swing.JRadioButton rdnu;
    private javax.swing.JRadioButton rdquanli;
    private javax.swing.JTable tableNhanVien;
    private javax.swing.JTextField txtcccd;
    private javax.swing.JTextField txtdiachi;
    private javax.swing.JTextField txthoten;
    private javax.swing.JTextField txtmatkhau;
    private javax.swing.JTextField txtsdt;
    private javax.swing.JTextField txttimkiemten;
    // End of variables declaration//GEN-END:variables
}
